# Generated by Django 5.0.2 on 2024-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actiontaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanon', models.CharField(max_length=100)),
                ('fanoff', models.CharField(max_length=100)),
                ('lighton', models.CharField(max_length=100)),
                ('lightoff', models.CharField(max_length=100)),
                ('acon', models.CharField(max_length=100)),
                ('acoff', models.CharField(max_length=100)),
                ('emergencyalarm', models.CharField(max_length=100)),
                ('bedorientation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Addpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevhist', models.CharField(max_length=100)),
                ('curcond', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('bystandname', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=100)),
            ],
        ),
    ]
